-- MySQL Script generated by MySQL Workbench
-- 04/25/16 12:55:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sECRgnCD` VARCHAR(45) NOT NULL,
  `firmCrdNb` VARCHAR(45) NOT NULL,
  `sECNb` VARCHAR(45) NOT NULL,
  `busNm` VARCHAR(100) NOT NULL,
  `legalNm` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mainAddr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mainAddr` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mainAddr` (
  `id_mainAddr` INT NOT NULL AUTO_INCREMENT,
  `strt1` VARCHAR(100) NOT NULL,
  `strt2` VARCHAR(100) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `cntry` VARCHAR(45) NOT NULL,
  `postlCd` VARCHAR(45) NOT NULL,
  `phNb` VARCHAR(45) NOT NULL,
  `info_id` INT NOT NULL,
  PRIMARY KEY (`id_mainAddr`, `info_id`),
  UNIQUE INDEX `id_mainAddr_UNIQUE` (`id_mainAddr` ASC),
  INDEX `fk_mainAddr_info_idx` (`info_id` ASC),
  CONSTRAINT `fk_mainAddr_info`
    FOREIGN KEY (`info_id`)
    REFERENCES `mydb`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rgstn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rgstn` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rgstn` (
  `id_rgstn` INT NOT NULL AUTO_INCREMENT,
  `firmtype` VARCHAR(45) NOT NULL,
  `st` VARCHAR(45) NOT NULL,
  `dt` DATE NOT NULL,
  `info_id` INT NOT NULL,
  PRIMARY KEY (`id_rgstn`, `info_id`),
  UNIQUE INDEX `id_rgstn_UNIQUE` (`id_rgstn` ASC),
  INDEX `fk_rgstn_info1_idx` (`info_id` ASC),
  CONSTRAINT `fk_rgstn_info1`
    FOREIGN KEY (`info_id`)
    REFERENCES `mydb`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`filing` ;

CREATE TABLE IF NOT EXISTS `mydb`.`filing` (
  `id_filing` INT NOT NULL AUTO_INCREMENT,
  `dt` DATE NOT NULL,
  `formVrsn` DATE NOT NULL,
  `info_id` INT NOT NULL,
  PRIMARY KEY (`id_filing`, `info_id`),
  UNIQUE INDEX `idfiling_UNIQUE` (`id_filing` ASC),
  INDEX `fk_filing_info1_idx` (`info_id` ASC),
  CONSTRAINT `fk_filing_info1`
    FOREIGN KEY (`info_id`)
    REFERENCES `mydb`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`states` ;

CREATE TABLE IF NOT EXISTS `mydb`.`states` (
  `id_states` INT NOT NULL AUTO_INCREMENT,
  `rgltrCd` VARCHAR(45) NOT NULL,
  `st` VARCHAR(45) NOT NULL,
  `dt` DATE NOT NULL,
  `info_id` INT NOT NULL,
  PRIMARY KEY (`id_states`, `info_id`),
  UNIQUE INDEX `idstates_UNIQUE` (`id_states` ASC),
  INDEX `fk_states_info1_idx` (`info_id` ASC),
  CONSTRAINT `fk_states_info1`
    FOREIGN KEY (`info_id`)
    REFERENCES `mydb`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item1` (
  `id_item1` INT NOT NULL AUTO_INCREMENT,
  `q1I` BIT(1) NOT NULL,
  `q1M` BIT(1) NOT NULL,
  `q1N` BIT(1) NOT NULL,
  `q1O` BIT(1) NOT NULL,
  `info_id` INT NOT NULL,
  PRIMARY KEY (`id_item1`, `info_id`),
  UNIQUE INDEX `iditem1_UNIQUE` (`id_item1` ASC),
  INDEX `fk_item1_info1_idx` (`info_id` ASC),
  CONSTRAINT `fk_item1_info1`
    FOREIGN KEY (`info_id`)
    REFERENCES `mydb`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`webAddr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`webAddr` ;

CREATE TABLE IF NOT EXISTS `mydb`.`webAddr` (
  `id_webAddr` INT NOT NULL AUTO_INCREMENT,
  `webAddr` VARCHAR(1000) NOT NULL,
  `info_id` INT NOT NULL,
  PRIMARY KEY (`id_webAddr`, `info_id`),
  UNIQUE INDEX `id_webAddr_UNIQUE` (`id_webAddr` ASC),
  INDEX `fk_webAddr_info1_idx` (`info_id` ASC),
  CONSTRAINT `fk_webAddr_info1`
    FOREIGN KEY (`info_id`)
    REFERENCES `mydb`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item2A`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item2A` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item2A` (
  `id_item2A` INT NOT NULL AUTO_INCREMENT,
  `q1A1` VARCHAR(45) NOT NULL,
  `q2A2` VARCHAR(45) NOT NULL,
  `q2A3` VARCHAR(45) NOT NULL,
  `q2A4` VARCHAR(45) NOT NULL,
  `q2A5` VARCHAR(45) NOT NULL,
  `q2A6` VARCHAR(45) NOT NULL,
  `q2A7` VARCHAR(45) NOT NULL,
  `q2A8` VARCHAR(45) NOT NULL,
  `q2A9` VARCHAR(45) NOT NULL,
  `q2A10` VARCHAR(45) NOT NULL,
  `q2A11` VARCHAR(45) NOT NULL,
  `q2A12` VARCHAR(45) NOT NULL,
  `q2A13` VARCHAR(45) NOT NULL,
  `info_id` INT NOT NULL,
  PRIMARY KEY (`id_item2A`, `info_id`),
  UNIQUE INDEX `id_item2A_UNIQUE` (`id_item2A` ASC),
  INDEX `fk_item2A_info1_idx` (`info_id` ASC),
  CONSTRAINT `fk_item2A_info1`
    FOREIGN KEY (`info_id`)
    REFERENCES `mydb`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item2B`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item2B` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item2B` (
  `id_item2B` INT NOT NULL AUTO_INCREMENT,
  `Q2B1` VARCHAR(45) NOT NULL,
  `Q2B2` VARCHAR(45) NOT NULL,
  `Q2B3` VARCHAR(45) NOT NULL,
  `info_id` INT NOT NULL,
  PRIMARY KEY (`id_item2B`, `info_id`),
  UNIQUE INDEX `id_item2B_UNIQUE` (`id_item2B` ASC),
  INDEX `fk_item2B_info1_idx` (`info_id` ASC),
  CONSTRAINT `fk_item2B_info1`
    FOREIGN KEY (`info_id`)
    REFERENCES `mydb`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item3A`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item3A` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item3A` (
  `id_item3A` INT NOT NULL AUTO_INCREMENT,
  `OrgFormNm` VARCHAR(45) NOT NULL,
  `info_id` INT NOT NULL,
  PRIMARY KEY (`id_item3A`, `info_id`),
  UNIQUE INDEX `id_item3A_UNIQUE` (`id_item3A` ASC),
  INDEX `fk_item3A_info1_idx` (`info_id` ASC),
  CONSTRAINT `fk_item3A_info1`
    FOREIGN KEY (`info_id`)
    REFERENCES `mydb`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
